apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |
    {
      "platform": "github",
      "endpoint": "https://api.github.com",
      "autodiscover": false,
      "repositories": [],
      "gitAuthor": "Renovate Bot <renovate@renovate.invalid>",
      "rebaseWhen": "conflicted",
      "timezone": "Europe/Berlin"
    }
