apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik
  namespace: authentik
spec:
  secretName: authentik-tls
  dnsNames:
    - authentik.licht
    - authentik.licht.moe
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
