---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aghome-config
  namespace: aghome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aghome-work
  namespace: aghome
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
