apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.licht
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
