apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm/
    targetRevision: 7.8.2
    helm:
      parameters:
        - name: configs.params.server.disable.auth
          value: 'true'
        - name: configs.params.server.insecure
          value: 'true'
    chart: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
