apiVersion: v1
kind: Namespace
metadata:
  name: teruko
---
apiVersion: v1
kind: Service
metadata:
  name: teruko
  namespace: teruko
spec:
  type: ExternalName
  externalName: tsubasa
  ports:
    - port: 7777
      targetPort: 7777
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teruko
  namespace: teruko
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`teruko`)
      services:
        - name: teruko
          port: 7777
  tls:
    certResolver: default
