apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 34.3.0
    helm:
      parameters:
        - name: ingressRoute.dashboard.enabled
          value: 'true'
        - name: ports.web.nodePort
          value: '80'
        - name: ports.websecure.nodePort
          value: '443'
        - name: ports.traefik.expose.default
          value: 'true'
        - name: service.type
          value: NodePort
    chart: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
