apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - certificate.yaml
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
