apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: openclaw
  namespace: openclaw
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`claw.licht.moe`)
      services:
        - name: openclaw
          port: 18789
  tls:
    secretName: openclaw-tls
