apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-provider-auth
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
