apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litellm-provider-auth
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    {{- toYaml .Values.providerAuthStorage.accessModes | nindent 4 }}
  {{- if eq .Values.providerAuthStorage.storageClassName "-" }}
  storageClassName: ""
  {{- else if .Values.providerAuthStorage.storageClassName }}
  storageClassName: {{ .Values.providerAuthStorage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.providerAuthStorage.size | quote }}
