apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
  labels:
    app: valkey
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
    - name: tcp
      protocol: TCP
      port: 6379
      targetPort: tcp
