apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:12.3.2-ubi
          imagePullPolicy: IfNotPresent
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: MARIADB_DATABASE
              value: "mariadb"
            - name: MARIADB_USER
              value: "mariadb"
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: user-password
            - name: TZ
              value: "Europe/Berlin"
          ports:
            - name: mariadb
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            exec:
              command:
                - /bin/bash
                - -c
                - mariadb-admin ping -u root
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - /bin/bash
                - -c
                - mariadb-admin ping -u root
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-pvc
