apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
  - certificate.yaml
  - deployment.yaml
  - namespace.yaml
  - route.yaml
  - service.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - mta-sts.conf
      - mta-sts.txt
      - remove-www.conf
