apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/argo-cd
    targetRevision: HEAD
    helm:
      valuesObject:
        argo-cd:
          configs:
            params:
              server.disable.auth: true
              server.insecure: true
        hostnames:
          - argocd.licht
          - argocd.hizuru.licht
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
