apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hizuru-authentik-outpost
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/authentik-outpost
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik-outpost
