apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hizuru-gateway-api
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    path: config/crd/standard
    targetRevision: v1.5.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
