apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/jellyfin
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
