traefik:
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    web:
      nodePort: 80
    websecure:
      nodePort: 443
      transport:
        respondingTimeouts:
          readTimeout: 180s
    traefik:
      expose:
        default: true
  service:
    spec:
      type: "NodePort"
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesGateway:
      enabled: true
  gateway:
    listeners:
      web:
        namespacePolicy:
          from: All
