apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  secretName: pgadmin-tls
  dnsNames:
    - pgadmin.licht
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
