apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`pgadmin.licht`)
      services:
        - name: pgadmin
          port: 80
  tls:
    secretName: pgadmin-tls
