apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teruko
  namespace: teruko
spec:
  secretName: teruko-tls
  dnsNames:
    - teruko.licht
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
