apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teruko
  namespace: teruko
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`teruko`)
      services:
        - name: teruko
          port: 7777
  tls:
    secretName: teruko-tls
