apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: teruko
  namespace: teruko
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`teruko.licht`)
      middlewares:
        - name: authentik-forward-auth
          namespace: traefik
      services:
        - name: teruko
          port: 3000
  tls:
    secretName: teruko-tls
