apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shinobu-local-path-provisioner
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner
    path: deploy/chart/local-path-provisioner
    targetRevision: v0.0.33
    helm:
      valuesObject:
        storageClass:
          defaultClass: true
  destination:
    server: https://shinobu:6443
    namespace: local-path-storage
