apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/postgres
    targetRevision: HEAD
  destination:
    server: https://shinobu:6443
    namespace: traefik
