apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: llm
  namespace: llm
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`llm.licht`)
      services:
        - name: llm
          port: http
  tls:
    secretName: llm-tls
