apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  secretName: jellyseerr-tls
  dnsNames:
    - jellyseerr.licht
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
