apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seerr
  namespace: jellyseerr
spec:
  secretName: seerr-tls
  dnsNames:
    - seerr.licht
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
