apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: jellyseerr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jellyseerr`)
      services:
        - name: jellyseerr
          port: 5055
  tls:
    secretName: jellyseerr-tls
