apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jellyseerr
  labels:
    app: jellyseerr
spec:
  selector:
    app: jellyseerr
  ports:
    - name: jellyseerr
      protocol: TCP
      port: 5055
      targetPort: jellyseerr
  type: ClusterIP
