apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}-cert-manager
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/cert-manager
    targetRevision: HEAD
    helm:
      parameters:
        - name: caIssuer.enabled
          value: "true"
        - name: acmeIssuer.enabled
          value: "true"
  destination:
    server: {{ .Values.cluster.address }}
    namespace: cert-manager
