apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}-cilium
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: oci://quay.io/cilium/charts/cilium
    path: .
    targetRevision: 1.19.6
    helm:
      valuesObject:
        bpf:
          masquerade: true
        cluster:
          name: sumireko
        hubble:
          enabled: true
          relay:
            enabled: true
          ui:
            enabled: true
        ipam:
          mode: kubernetes
          operator:
            clusterPoolIPv4PodCIDRList: 10.244.0.0/16
            clusterPoolIPv6PodCIDRList: 10.96.0.0/12
        ipv4:
          enabled: true
        ipv6:
          enabled: true
        ipv6NativeRoutingCIDR: 2001:db8:42:0::/56
        k8sServiceHost: 217.182.193.134
        k8sServicePort: 6443
        kubeProxyReplacement: true
        nodeinit:
          enabled: true
        operator:
          replicas: 1
  destination:
    server: {{ .Values.cluster.address }}
    namespace: kube-system
