apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}-forge
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    path: apps/forge
    targetRevision: HEAD
  destination:
    server: {{ .Values.cluster.address }}
    namespace: forge
