apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}-renovate
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    targetRevision: HEAD
    path: apps/renovate
  destination:
    server: {{ .Values.cluster.address }}
    namespace: renovate
