apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Chart.Name }}-renovate
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/Lichthagel/infra
    targetRevision: HEAD
    path: apps/renovate
    helm:
      valuesObject:
        instances:
          github:
            schedule: "0 0,8,12,16,20 * * *"
            timeZone: Europe/Berlin
  destination:
    server: {{ .Values.cluster.address }}
    namespace: renovate
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
