{{- range $name, $instance := .Values.instances }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-{{ $name }}
  namespace: renovate
  labels:
    app: renovate
spec:
  schedule: {{ $instance.schedule | quote }}
  timeZone: {{ default "Europe/Berlin" $instance.timeZone | quote }}
  concurrencyPolicy: "Allow"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      activeDeadlineSeconds: 6300
      template:
        metadata:
          labels:
            app: renovate
        spec:
          serviceAccountName: renovate
          restartPolicy: Never
          containers:
            - name: renovate
              image: ghcr.io/renovatebot/renovate:43.273.0
              imagePullPolicy: IfNotPresent
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: /usr/src/app/config.json
                - name: TZ
                  value: {{ default "Europe/Berlin" $instance.timeZone | quote }}
                - name: LOG_LEVEL
                  value: {{ default "info" $instance.logLevel }}
              envFrom:
                - secretRef:
                    name: renovate-{{ $name }}-secret
              volumeMounts:
                - name: config
                  mountPath: /usr/src/app/config.json
                  subPath: config.json
                - name: cache
                  mountPath: /tmp/renovate
          volumes:
            - name: config
              configMap:
                name: renovate-{{ $name }}-config
            - name: cache
              persistentVolumeClaim:
                claimName: renovate-{{ $name }}-cache
          securityContext:
            fsGroup: 1000
          terminationGracePeriodSeconds: 6300
---
{{- end }}
