{{- range $name, $instance := .Values.instances }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}-cache
  namespace: renovate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
{{- end }}
