apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  secretName: argo-cd-tls
  dnsNames: {{ .Values.hostnames | toYaml | nindent 4 }}
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
