apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-cd-server
  namespace: argo-cd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ range $index, $host := .Values.hostnames }}{{ if $index }} || {{ end }}Host(`{{ $host }}`){{ end }}
      priority: 10
      services:
        - name: {{ .Release.Name }}-argocd-server
          port: 80
    - kind: Rule
      match: ({{ range $index, $host := .Values.hostnames }}{{ if $index }} || {{ end }}Host(`{{ $host }}`){{ end }}) && Header(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: {{ .Release.Name }}-argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argo-cd-tls
