apiVersion: v1
kind: ConfigMap
metadata:
  name: netbird-config
  namespace: netbird
data:
  config.yaml: |
    server:
      listenAddress: ":80"
      exposedAddress: "https://netbird.licht.moe"
      stunPorts:
        - 3478
      dataDir: /var/lib/netbird
      store:
        engine: "postgres"
      authStore:
        engine: "postgres"
      activityStore:
        engine: "postgres"
