apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbird-server
  namespace: netbird
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbird-server
  template:
    metadata:
      labels:
        app: netbird-server
    spec:
      containers:
        - name: netbird-server
          image: docker.io/netbirdio/netbird-server:0.75.0
          args:
            - --config
            - /etc/netbird/config.yaml
          env:
            - name: NETBIRD_STORE_ENGINE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: netbird-postgres
                  key: dsn
            - name: NETBIRD_AUTH_STORE_ENGINE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: netbird-postgres
                  key: dsn_idp
            - name: NETBIRD_ACTIVITY_STORE_ENGINE_POSTGRES_DSN
              valueFrom:
                secretKeyRef:
                  name: netbird-postgres
                  key: dsn_activity
            - name: NETBIRD_SERVER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: netbird-postgres
                  key: authSecret
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: stun
              containerPort: 3478
              hostPort: 3478
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/netbird/config.yaml
              subPath: config.yaml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: netbird-config
