apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hono
  namespace: hono
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`hono.gatzweiler.xyz`)
      services:
        - name: hono
          port: 8000
