apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr
  namespace: homarr
spec:
  secretName: homarr-tls
  dnsNames:
    - homarr
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
