apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homarr
  namespace: homarr
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homarr`)
      services:
        - name: homarr
          port: 7575
  tls:
    secretName: homarr-tls
