{{- if .Values.nginx.passthrough -}}
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: traefik
spec:
  type: ExternalName
  externalName: shinobu
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
{{- end -}}
